//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CustomerMovies = new HashSet<CustomerMovie>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public bool IsSubscribedNewsLetter { get; set; }
        public byte MembershipTypeId { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerMovie> CustomerMovies { get; set; }
        public virtual MembershipType MembershipType { get; set; }
    }
}
